services:
  - type: web
    name: tuneload-server
    env: node
    plan: free
    buildCommand: npm install && pip3 install yt-dlp || python3 -m pip install yt-dlp || curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp
    startCommand: node index.js
